export const REALISTIC_ALUMNI = [
  { last: "ABAD", first: "MICA", middle: "CAJELO", course: "Bachelor of Elementary Education", grad: "2021", email: "martinalanchapie@gmail.com" },
  { last: "ABEJON", first: "R-JAY", middle: "TATAC", course: "Bachelor of Elementary Education", grad: "2021", email: "rjay02@ymail.com" },
  { last: "ALTAJARA", first: "JENELYN", middle: "POLBORIDO", course: "Bachelor of Elementary Education", grad: "2021", email: "jennyaltajara01@gmail.com" },
  { last: "ARNOCO", first: "GERALDINE", middle: "MORCILLA", course: "Bachelor of Elementary Education", grad: "2021", email: "geraldinearnoco08@gmail.com" },
  { last: "BORBE", first: "JUDY ANNE", middle: "TIMOG", course: "Bachelor of Elementary Education", grad: "2021", email: "kliam884@gmail.com" },
  { last: "CALLO JR.", first: "APOLINAR", middle: "GAMBITO", course: "Bachelor of Elementary Education", grad: "2021", email: "callodhon9@gmail.com" },
  { last: "DALMAOB", first: "NORHAINA", middle: "SAILILA", course: "Bachelor of Elementary Education", grad: "2021", email: "norhainasaililadalmaob@gmail.com" },
  { last: "DE CHAVEZ", first: "CYNDIE", middle: "QUINTERO", course: "Bachelor of Elementary Education", grad: "2021", email: "dechavezcyndieq@gmail.com" },
  { last: "DE RAMOS", first: "ARCEL CHRISTLYANNE", middle: "SORIANO", course: "Bachelor of Elementary Education", grad: "2021", email: "rclderamos@gmail.com" },
  { last: "EDILLOR", first: "MARELA MARIE", middle: "SANGALANG", course: "Bachelor of Elementary Education", grad: "2021", email: "marelamariee@gmail.com" },
  { last: "MACATYAG", first: "JENRIE", middle: "LOCSIN", course: "Bachelor of Science in Information Technology", grad: "2021", email: "jj_mc11@yahoo.com" },
  { last: "MADRAZO", first: "JOEL", middle: "DE JESUS", course: "Bachelor of Science in Information Technology", grad: "2021", email: "madrazo1997@gmail.com" },
  { last: "MAHINAY", first: "BEVERLY", middle: "SALVADOR", course: "Bachelor of Science in Information Technology", grad: "2021", email: "beverlymahinay0802@gmail.com" },
  { last: "OPINA", first: "MARK JOSEPH", middle: "BALTAZAR", course: "Bachelor of Science in Information Technology", grad: "2021", email: "mc.opina3@gmail.com" },
  { last: "ORENCIA", first: "CRIS", middle: "DIEGO", course: "Bachelor of Science in Information Technology", grad: "2021", email: "kyohei.issei@gmail.com" },
  { last: "ORIJOLA", first: "CHRISTINE JADE", middle: "", course: "Bachelor of Science in Information Technology", grad: "2021", email: "CjOrijola0199@gmail.com" },
  { last: "BALASOTO", first: "RAYMART", middle: "VILLANUEVA", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "balasoto.raymart923@gmail.com" },
  { last: "CAPISTRANO", first: "PAUL ARCEE", middle: "LABATOS", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "paularceecapistrano@gmail.com" },
  { last: "CATALON", first: "KEN", middle: "SAN MARTIN", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "knsmcat@gmail.com" },
  { last: "CODOY", first: "FRANCIA", middle: "GUIANG", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "ciacodoy@gmail.com" },
  { last: "CONSTANTINO", first: "MIKE JORDAN", middle: "LIBANG", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "mikejordanconstantino@gmail.com" },
  { last: "DEL ROSARIO", first: "CZAR KARL JOSEF", middle: "SUELTO", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "dczarkarl@yahoo.com" },
  { last: "PECAÑA", first: "Karlo", middle: "Abaño", course: "Bachelor of Science in Entrepreneurship", grad: "2021", email: "Carlopecana@yahoo.com" },
  { last: "AGRA", first: "LAUDERDALE", middle: "VALDELLON", course: "Bachelor of Science in Entrepreneurship", grad: "2021", email: "lauderdale553@gmail.com" },
  { last: "ALVARAN", first: "CRISTINE MEA", middle: "VISUYAN", course: "Bachelor of Science in Entrepreneurship", grad: "2021", email: "cristinemea0303@gmail.com" },
  { last: "APILADO", first: "MA. NICOLE", middle: "SOLA", course: "Bachelor of Science in Entrepreneurship", grad: "2021", email: "solanicole252@gmail.com" },
  { last: "APILADO", first: "MARC DANIEL ERICK", middle: "SOLA", course: "Bachelor of Science in Entrepreneurship", grad: "2021", email: "Mapilado1226@yahoo.com" },
  { last: "CANTO", first: "HUBBERT", middle: "MONECIA", course: "Bachelor of Science in Entrepreneurship", grad: "2021", email: "Hubbertmonecia@gmail.com" },
  { last: "BISCO", first: "CHRISTIAN JOSHUA", middle: "MODENA", course: "Bachelor of Arts in Communication", grad: "2021", email: "joshuabisco26@gmail.com" },
  { last: "CABILLON", first: "JERICK", middle: "GAYNILO", course: "Bachelor of Arts in Communication", grad: "2021", email: "jerick7267241@gmail.com" },
  { last: "FERRER", first: "AJAY", middle: "ARIAS", course: "Bachelor of Arts in Communication", grad: "2021", email: "ajay.arias@gmail.com" },
  { last: "RAMOS", first: "JAN JOSEFF", middle: "EDEC", course: "Bachelor of Arts in Communication", grad: "2021", email: "ramosjanjoseff@gmail.com" },
  { last: "TUYOR", first: "EDWARD", middle: "LAMBOSON", course: "Bachelor of Arts in Communication", grad: "2021", email: "edwardtuyor10@gmail.com" },
  { last: "REGALARIO", first: "ANGELICA", middle: "ADVINCULA", course: "Bachelor of Science in Computer Science", grad: "2021", email: "aadvincula128@gmail.com" },
  { last: "CAYMO", first: "JOSEPH MALCOLM", middle: "SASUAN", course: "Bachelor of Science in Computer Science", grad: "2022", email: "jmcaymo2@gmail.com" },
  { last: "DORADO", first: "MARY BELLE", middle: "VERIDIANO", course: "Bachelor of Science in Computer Science", grad: "2022", email: "marybelledorado@gmail.com" },
  { last: "ESCOSURA", first: "KENN DARYL", middle: "RAYOS", course: "Bachelor of Science in Computer Science", grad: "2022", email: "kenndarylescosura@gmail.com" },
  { last: "ESGUERRA", first: "LEONEL", middle: "REYES", course: "Bachelor of Science in Computer Science", grad: "2022", email: "leonelesguerra0401@gmail.com" },
  { last: "CALANZA", first: "CHARLES ADRIAN", middle: "ABAY", course: "Bachelor of Science in Mechanical Engineering", grad: "2024", email: "charlesadriancalanza@gmail.com" },
  { last: "CANLAS", first: "JOSHUA MITCHELLE", middle: "DE LEON", course: "Bachelor of Science in Mechanical Engineering", grad: "2024", email: "joshuacanlas72@gmail.com" },
  { last: "CANTIGA", first: "ADRIAN", middle: "DE LA CRUZ", course: "Bachelor of Science in Mechanical Engineering", grad: "2024", email: "cantiga.adrian@gmail.com" },
  { last: "ABLIS", first: "JOEMARC", middle: "AGRIPA", course: "Bachelor of Science in Accounting Information System", grad: "2022", email: "jjjoemarcablis@gmail.com" },
  { last: "ABSALON", first: "CARLA JANE", middle: "CALIWAG", course: "Bachelor of Science in Accounting Information System", grad: "2022", email: "16carlajaneabsalon@gmail.com" },
  { last: "ALEÑO", first: "MA. ELISA", middle: "BERZUELA", course: "Bachelor of Science in Accounting Information System", grad: "2022", email: "maelisaaleno@yahoo.com" },
  { last: "CONSTANTINO", first: "JANE ANTONETTE", middle: "BABAAN", course: "Bachelor of Science in Accountancy", grad: "2022", email: "onitnatsnocenaj@gmail.com" },
  { last: "CORONADO", first: "ROMELYNE", middle: "LACERNA", course: "Bachelor of Science in Accountancy", grad: "2022", email: "romelynelacernacoronado4@gmail.com" },
  { last: "CUBELO", first: "GENE AILEEN", middle: "AMPO", course: "Bachelor of Science in Accountancy", grad: "2022", email: "cubelogeneaileen@gmail.com" },
  { last: "ENDIZA", first: "LIZ NICOLE", middle: "LUCENA", course: "Bachelor of Elementary Education", grad: "2021", email: "llucena.bos@gmail.com" },
  { last: "ESPINOLA", first: "MARY GRACE", middle: "BACOBE", course: "Bachelor of Elementary Education", grad: "2021", email: "marygraceespinola00@gmail.com" },
  { last: "FAJARDO", first: "PATRICK DAVE", middle: "CALIBO", course: "Bachelor of Elementary Education", grad: "2021", email: "fajardopdc05@yahoo.com" },
  { last: "FAUSTINO", first: "NEIL", middle: "MATIENZO", course: "Bachelor of Elementary Education", grad: "2021", email: "matienzoneil939@gmail.com" },
  { last: "FRANCO", first: "JESSICA PAULINE", middle: "SALES", course: "Bachelor of Elementary Education", grad: "2021", email: "jessicapaulinefranco@yahoo.com" },
  { last: "GARTNER", first: "CHRISTIAN", middle: "GONZALES", course: "Bachelor of Elementary Education", grad: "2021", email: "guardiandeno@gmail.com" },
  { last: "GRANADA", first: "JOANA LYN", middle: "DASIGAO", course: "Bachelor of Elementary Education", grad: "2021", email: "jlyngranada@gmail.com" },
  { last: "GREGORIO", first: "JOSHUA", middle: "HELERA", course: "Bachelor of Elementary Education", grad: "2021", email: "gregoriojoshua920@gmail.com" },
  { last: "ISIDRO", first: "ANABEL", middle: "BANTANG", course: "Bachelor of Elementary Education", grad: "2021", email: "nafedhel1618@gmail.com" },
  { last: "JAVIER", first: "CHERIE MAE", middle: "SAN JOSE", course: "Bachelor of Elementary Education", grad: "2021", email: "cheriemaejavier@yahoo.com.ph" },
  { last: "JOVELLANO", first: "KEIANNE NICOLE", middle: "VARIN", course: "Bachelor of Elementary Education", grad: "2021", email: "keiannejovellano@gmail.com" },
  { last: "LIMONERAS", first: "JUDE ZYRON", middle: "CORONADO", course: "Bachelor of Elementary Education", grad: "2021", email: "sanaminatozakiharthart@gmail.com" },
  { last: "LIPATA", first: "MABEL", middle: "DORADO", course: "Bachelor of Elementary Education", grad: "2021", email: "mabellipata7@gmail.com" },
  { last: "MAMPUSTI", first: "MARIA LOU SHIELA", middle: "OFIASA", course: "Bachelor of Elementary Education", grad: "2021", email: "marialoushielamampusti@gmail.com" },
  { last: "MARIMUTHU", first: "JOSHUA", middle: "CUSTODIO", course: "Bachelor of Elementary Education", grad: "2021", email: "jcmarimuthu@gmail.com" },
  { last: "MONTILLA", first: "NORAZEL", middle: "COSIO", course: "Bachelor of Elementary Education", grad: "2021", email: "chemontillano@gmail.com" },
  { last: "OBEL", first: "REGINE", middle: "CORALES", course: "Bachelor of Elementary Education", grad: "2021", email: "regineobel_1218@yahoo.com" },
  { last: "OCA", first: "JURICE REINEAL", middle: "ZOTOMAYOR", course: "Bachelor of Elementary Education", grad: "2021", email: "juricereineal@yahoo.com" },
  { last: "PALIZA", first: "JANINE", middle: "", course: "Bachelor of Elementary Education", grad: "2021", email: "nininpalizamendoza@gmail.com" },
  { last: "PORTUGAL", first: "JOAN", middle: "RELUCANO", course: "Bachelor of Elementary Education", grad: "2021", email: "joanportugal91@gmail.com" },
  { last: "PUNZALAN", first: "JAN DEREC", middle: "TESORERO", course: "Bachelor of Elementary Education", grad: "2021", email: "janderecp@gmail.com" },
  { last: "REBANO", first: "APRIL", middle: "BARBECHO", course: "Bachelor of Elementary Education", grad: "2021", email: "aprilrebano07@gmail.com" },
  { last: "REYES", first: "ROSE ANGELA", middle: "KMATOY", course: "Bachelor of Elementary Education", grad: "2021", email: "roseangelareyes.03@gmail.com" },
  { last: "RIVERA", first: "ZIARA MAE", middle: "DELA CRUZ", course: "Bachelor of Elementary Education", grad: "2021", email: "ziaramaerivera48@gmail.com" },
  { last: "SOBREVIÑAS", first: "JOAN", middle: "COBRANA", course: "Bachelor of Elementary Education", grad: "2021", email: "ebengsobrevinas02@gmail.com" },
  { last: "TALLADA", first: "NERISSA", middle: "EBUENGA", course: "Bachelor of Elementary Education", grad: "2021", email: "nerissatallada@gmail.com" },
  { last: "TITAN", first: "CLAUDINE", middle: "RAMOS", course: "Bachelor of Elementary Education", grad: "2021", email: "claudine.titan@yahoo.com" },
  { last: "LACSON", first: "KRISTINE ANNE", middle: "DICHE", course: "Bachelor of Secondary Education major in Biological Science", grad: "2021", email: "kristineannelacson@gmail.com" },
  { last: "SALOFRANIA", first: "EDUARDO", middle: "MANGAY", course: "Bachelor of Secondary Education major in Biological Science", grad: "2021", email: "salofrania@yahoo.com" },
  { last: "AURIN", first: "RONA JANE", middle: "LOTINO", course: "Bachelor of Science in Accounting Technology", grad: "2021", email: "aurinronajane@gmail.com" },
  { last: "SABLAON", first: "PAULA JOY", middle: "DAVE", course: "Bachelor of Science in Accounting Technology", grad: "2021", email: "sablaonpaulajoy@gmail.com" },
  { last: "CAVAN", first: "James", middle: "Mabuyo", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "megscavan24@yahoo.com" },
  { last: "CRUZ", first: "Denzel", middle: "Pambago", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "denzelcruz26@gmail.com" },
  { last: "MILO", first: "Jairus Joriel", middle: "Almario", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "milojairus@gmail.com" },
  { last: "REY", first: "Christian Paulo", middle: "Martinez", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "reychris13@gmail.com" },
  { last: "SANTOS", first: "Aynrand Van", middle: "Montalban", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "aynrandvanss@gmail.com" },
  { last: "SEÑADOZA", first: "Manolito Jr.", middle: "Añil", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "manolitosenadozajr@gmail.com" },
  { last: "APATAN", first: "JOSHUA", middle: "TABIOS", course: "Bachelor of Science in Mechanical Engineering", grad: "2021", email: "ninjamaster04@yahoo.com" },
  { last: "DACDAC", first: "ROSEHEART COLLINE", middle: "CALIMAG", course: "Bachelor of Science in Accountancy", grad: "2022", email: "roseheartcollinedacdac@gmail.com" },
  { last: "DAYAHAN", first: "SHAMEI", middle: "GERARDO", course: "Bachelor of Science in Accountancy", grad: "2022", email: "shameigerardodayahan@gmail.com" },
  { last: "DE CHAVEZ", first: "SELINA", middle: "YUTUC", course: "Bachelor of Science in Accountancy", grad: "2022", email: "dechavezselina78@gmail.com" },
  { last: "DE GUZMAN", first: "MARION MACARIUS", middle: "MIRANDA", course: "Bachelor of Science in Accountancy", grad: "2022", email: "maru41094@gmail.com" },
  { last: "DE RAMA", first: "ALLYSA JEM", middle: "MANANGKIL", course: "Bachelor of Science in Accountancy", grad: "2022", email: "ajderama27@gmail.com" },
  { last: "DIMAANO", first: "THRICIA MAE", middle: "KAMATOY", course: "Bachelor of Science in Accountancy", grad: "2022", email: "dmn.thriciamae@gmail.com" },
  { last: "DORADO", first: "SHERLYN", middle: "MONSERRAT", course: "Bachelor of Science in Accountancy", grad: "2022", email: "sherlyndorado@gmail.com" },
  { last: "ERNIETA", first: "JARRIE ANN", middle: "ADVINCULA", course: "Bachelor of Science in Accountancy", grad: "2022", email: "jarrieannernieta@gmail.com" },
  { last: "ESQUERES", first: "LEUVIELYN", middle: "RAMOS", course: "Bachelor of Science in Accountancy", grad: "2022", email: "leahesqueres@gmail.com" },
  { last: "GACETA", first: "JUDY ANN", middle: "MAURIN", course: "Bachelor of Science in Accountancy", grad: "2022", email: "gacetajudyann@gmail.com" },
  { last: "GALLARDO", first: "WINNIE GRACE", middle: "RODRIGUEZ", course: "Bachelor of Science in Accountancy", grad: "2022", email: "win.gallardo31@gmail.com" },
  { last: "GARNEL", first: "RACHEL ELIZABETH", middle: "REUSQUILLO", course: "Bachelor of Science in Accountancy", grad: "2022", email: "garnelrachel03@gmail.com" },
  { last: "LAGURA", first: "JAMES RYAN", middle: "CABANTOG", course: "Bachelor of Science in Accountancy", grad: "2022", email: "rjaylagura@gmail.com" }
];
